SELECT TOP (1000) [ItemId]
      ,[ItemName]
      ,[ItemType]
      ,[QuantityAvailable]
      ,[QuantityTotal]
  FROM [master].[dbo].[Items]

SELECT TOP (1000) [LoanId]
      ,[ItemId]
      ,[UserId]
      ,[Quantity]
      ,[LoanDate]
      ,[DueDate]
      ,[ReturnDate]
  FROM [master].[dbo].[Loan]

SELECT TOP (1000) [UserId]
      ,[Username]
      ,[Password]
      ,[Role]
  FROM [master].[dbo].[Users]